import JSZip from 'jszip';

interface PluginManifest {
  readonly name: string;
  readonly version: string;
  readonly description: string;
  readonly agents: string;
  readonly skills: string;
}

interface PluginFile {
  readonly path: string;
  readonly content: string;
}

interface ExportInput {
  readonly projectName: string;
  readonly agents: readonly PluginFile[];
  readonly skills: readonly PluginFile[];
}

function buildManifest(projectName: string): PluginManifest {
  return {
    name: projectName,
    version: '1.0.0',
    description: 'Generated by cc-studio',
    agents: './agents/',
    skills: './skills/',
  };
}

function buildReadme(projectName: string, agentCount: number, skillCount: number): string {
  const lines = [
    `# ${projectName} Plugin`,
    '',
    `Generated by [cc-studio](https://github.com/nicepkg/cc-studio).`,
    '',
    '## Contents',
    '',
    `- **Agents**: ${agentCount}`,
    `- **Skills**: ${skillCount}`,
    '',
    '## Installation',
    '',
    'Copy the contents of this package into your project\'s `.claude/` directory.',
    '',
  ];
  return lines.join('\n');
}

export async function buildPluginZip(input: ExportInput): Promise<Blob> {
  const zip = new JSZip();
  const prefix = `${input.projectName}-plugin`;

  // plugin.json manifest
  const manifest = buildManifest(input.projectName);
  zip.file(
    `${prefix}/.claude-plugin/plugin.json`,
    JSON.stringify(manifest, null, 2) + '\n',
  );

  // Agents
  for (const agent of input.agents) {
    zip.file(`${prefix}/agents/${agent.path}`, agent.content);
  }

  // Skills
  for (const skill of input.skills) {
    zip.file(`${prefix}/skills/${skill.path}`, skill.content);
  }

  // README
  const readme = buildReadme(
    input.projectName,
    input.agents.length,
    input.skills.length,
  );
  zip.file(`${prefix}/README.md`, readme);

  return zip.generateAsync({ type: 'blob' });
}

export function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}
